name: Aggiorna Allerta Meteo

on:
  schedule:
    - cron: '0 * * * *' # ogni ora
  workflow_dispatch: # avvio manuale

jobs:
  aggiorna-allerta:
    runs-on: ubuntu-latest
    steps:
      - name: Clona il repository
        uses: actions/checkout@v3

      - name: Installa PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Scarica XML e genera JSON
        run: |
          php <<'EOF'
          <?php
          $xmlUrl = "https://allertameteo.regione.lazio.it/xml/allerta.xml";
          $zona_target = "E";

          $xml = @simplexml_load_file($xmlUrl);
          if (!$xml) {
              file_put_contents("allerta.json", json_encode(["errore" => "Impossibile caricare l'XML."]));
              exit(0);
          }

          $allerta = null;
          foreach ($xml->zona as $zona) {
              if ((string)$zona['id'] === $zona_target) {
                  $allerta = [
                      "zona" => (string)$zona['id'],
                      "validita" => (string)$zona->data,
                      "colore" => strtolower((string)$zona->allerta_colore),
                      "tipo" => (string)$zona->allerta_rischio
                  ];
                  break;
              }
          }

          if (!$allerta) {
              file_put_contents("allerta.json", json_encode(["errore" => "Zona non trovata."]));
          } else {
              file_put_contents("allerta.json", json_encode($allerta, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));
          }
          ?>
          EOF

      - name: Commit file JSON
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add allerta.json
          git commit -m "Aggiornamento allerta da Meteoalarm" || echo "Nessuna modifica"
          git push
