name: Update Allerta JSON

on:
  schedule:
    - cron: '0 * * * *'  # ogni ora
  workflow_dispatch:

jobs:
  fetch-allerta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Scarica dati da Meteoalarm
        run: |
          curl -s -o meteoalarm.json "https://www.meteoalarm.org/api/v1/warnings?country=IT"

      - name: Estrai allerta per Lazio
        run: |
          jq '[.[] | select(.region == "Lazio")][0]' meteoalarm.json > allerta.json || echo '{}' > allerta.json

      - name: Commit file JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add allerta.json
          git commit -m "Aggiornamento allerta da Meteoalarm" || echo "Nessuna modifica"
          git push
