name: Aggiorna Allerta Meteo Lazio

on:
  schedule:
    - cron: "0 * * * *" # ogni ora
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Scarica RSS Protezione Civile e genera JSON
        run: |
          curl -s -A "Mozilla/5.0" -o feed.xml https://www.protezionecivile.gov.it/export/risks/allertameteo/rss/allerta-it.xml
          php <<'EOF'
          <?php
          $xml = simplexml_load_file('feed.xml');
          $found = null;
          foreach ($xml->channel->item as $item) {
              if (strpos((string)$item->title, 'Lazio') !== false) {
                  $found = [
                      'titolo' => (string)$item->title,
                      'pubblicazione' => (string)$item->pubDate,
                      'descrizione' => strip_tags((string)$item->description)
                  ];
                  break;
              }
          }
          file_put_contents('allerta.json', json_encode($found ?: ['errore'=>'Nessuna allerta per il Lazio'], JSON_PRETTY_PRINT));
          EOF

      - name: Commit e push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add allerta.json
          git commit -m "Aggiornamento allerta da Protezione Civile" || echo "Nessuna modifica"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
